export const aboutUsPhotoSlider = [
  {
    photo: '/images/teachers/Andrii.jpeg',
    name: 'aboutUs.teachersName.Andrii',
    position: 'aboutUs.position.teacher',
    id: 0,
  },
  {
    photo: '/images/teachers/Dmytro.jpeg',
    name: 'aboutUs.teachersName.Dmytro',
    position: 'aboutUs.position.teacher',
    id: 1,
  },
  {
    photo: '/images/teachers/Georgiy.jpeg',
    name: 'aboutUs.teachersName.Georgiy',
    position: 'aboutUs.position.teacher',
    id: 2,
  },
  {
    photo: '/images/teachers/Iryna.jpeg',
    name: 'aboutUs.teachersName.Iryna',
    position: 'aboutUs.position.teacher',
    id: 3,
  },
  {
    photo: '/images/teachers/Mykhailo.jpeg',
    name: 'aboutUs.teachersName.Mykhailo',
    position: 'aboutUs.position.teacher',
    id: 4,
  },
  {
    photo: '/images/teachers/Mykhailo1.jpeg',
    name: 'aboutUs.teachersName.Mykhailo',
    position: 'aboutUs.position.teacher',
    id: 5,
  },
  {
    photo: '/images/teachers/Oleg.jpeg',
    name: 'aboutUs.teachersName.Oleg',
    position: 'aboutUs.position.teacher',
    id: 6,
  },
  {
    photo: '/images/teachers/Oleg1.jpeg',
    name: 'aboutUs.teachersName.Oleg',
    position: 'aboutUs.position.teacher',
    id: 7,
  },
  {
    photo: '/images/teachers/Phillip.jpeg',
    name: 'aboutUs.teachersName.Phillip',
    position: 'aboutUs.position.teacher',
    id: 8,
  },
  {
    photo: '/images/teachers/Sergii.jpeg',
    name: 'aboutUs.teachersName.Sergii',
    position: 'aboutUs.position.teacher',
    id: 9,
  },
  {
    photo: '/images/teachers/Volodymyr.jpeg',
    name: 'aboutUs.teachersName.Volodymyr',
    position: 'aboutUs.position.teacher',
    id: 10,
  },
  {
    photo: '/images/teachers/Andrii1.jpeg',
    name: 'aboutUs.teachersName.Andrii',
    position: 'aboutUs.position.instructor',
    id: 11,
  },
  {
    photo: '/images/teachers/Danylo.jpeg',
    name: 'aboutUs.teachersName.Danylo',
    position: 'aboutUs.position.instructor',
    id: 12,
  },
  {
    photo: '/images/teachers/Dmytro1.jpeg',
    name: 'aboutUs.teachersName.Dmytro',
    position: 'aboutUs.position.instructor',
    id: 14,
  },
  {
    photo: '/images/teachers/Kyrylo.jpeg',
    name: 'aboutUs.teachersName.Kyrylo',
    position: 'aboutUs.position.instructor',
    id: 15,
  },
  {
    photo: '/images/teachers/Maksym.jpeg',
    name: 'aboutUs.teachersName.Maksym',
    position: 'aboutUs.position.instructor',
    id: 16,
  },
  {
    photo: '/images/teachers/Mykola.jpeg',
    name: 'aboutUs.teachersName.Mykola',
    position: 'aboutUs.position.instructor',
    id: 17,
  },
  {
    photo: '/images/teachers/Sergii2.jpeg',
    name: 'aboutUs.teachersName.Sergii',
    position: 'aboutUs.position.instructor',
    id: 18,
  },
  {
    photo: '/images/teachers/Sergii1.jpeg',
    name: 'aboutUs.teachersName.Sergii',
    position: 'aboutUs.position.instructor',
    id: 19,
  },
  {
    photo: '/images/teachers/Vadym.jpeg',
    name: 'aboutUs.teachersName.Vadym',
    position: 'aboutUs.position.instructor',
    id: 20,
  },
  {
    photo: '/images/teachers/Volodymyr1.jpeg',
    name: 'aboutUs.teachersName.Volodymyr',
    position: 'aboutUs.position.instructor',
    id: 21,
  },
  {
    photo: '/images/teachers/Sergii3.jpeg',
    name: 'aboutUs.teachersName.Sergii',
    position: 'aboutUs.position.instructor',
    id: 22,
  },
];
