export const aboutUsPhotoSlider = [
  {
    photo: '/images/teachers/Andrii.jpeg',
    name: 'aboutUs.teachersName.Andrii',
    position: 'aboutUs.position.teacher',
    experience: '10 years',
    id: 0,
  },
  {
    photo: '/images/teachers/Dmytro.jpeg',
    name: 'aboutUs.teachersName.Dmytro',
    position: 'aboutUs.position.teacher',
    experience: '10 years',
    id: 1,
  },
  {
    photo: '/images/teachers/Georgiy.jpeg',
    name: 'aboutUs.teachersName.Georgiy',
    position: 'aboutUs.position.teacher',
    experience: '10 years',
    id: 2,
  },
  {
    photo: '/images/teachers/Iryna.jpeg',
    name: 'aboutUs.teachersName.Iryna',
    position: 'aboutUs.position.teacher',
    experience: '10 years',
    id: 3,
  },
  {
    photo: '/images/teachers/Mykhailo.jpeg',
    name: 'aboutUs.teachersName.Mykhailo',
    position: 'aboutUs.position.teacher',
    experience: '10 years',
    id: 4,
  },
  {
    photo: '/images/teachers/Mykhailo1.jpeg',
    name: 'aboutUs.teachersName.Mykhailo',
    position: 'aboutUs.position.teacher',
    experience: '10 years',
    id: 5,
  },
  {
    photo: '/images/teachers/Oleg.jpeg',
    name: 'aboutUs.teachersName.Oleg',
    position: 'aboutUs.position.teacher',
    experience: '10 years',
    id: 6,
  },
  {
    photo: '/images/teachers/Oleg1.jpeg',
    name: 'aboutUs.teachersName.Oleg',
    position: 'aboutUs.position.teacher',
    experience: '10 years',
    id: 7,
  },
  {
    photo: '/images/teachers/Phillip.jpeg',
    name: 'aboutUs.teachersName.Phillip',
    position: 'aboutUs.position.teacher',
    experience: '10 years',
    id: 8,
  },
  {
    photo: '/images/teachers/Sergii.jpeg',
    name: 'aboutUs.teachersName.Sergii',
    position: 'aboutUs.position.teacher',
    experience: '10 years',
    id: 9,
  },
  {
    photo: '/images/teachers/Volodymyr.jpeg',
    name: 'aboutUs.teachersName.Volodymyr',
    position: 'aboutUs.position.teacher',
    experience: '10 years',
    id: 10,
  },
];
